// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: jobconfigpb/embedded.proto

package jobconfigpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddedSource_GeneratorType int32

const (
	EmbeddedSource_GENERATOR_TYPE_UNSPECIFIED EmbeddedSource_GeneratorType = 0
	EmbeddedSource_GENERATOR_TYPE_SEQUENCE    EmbeddedSource_GeneratorType = 1
)

// Enum value maps for EmbeddedSource_GeneratorType.
var (
	EmbeddedSource_GeneratorType_name = map[int32]string{
		0: "GENERATOR_TYPE_UNSPECIFIED",
		1: "GENERATOR_TYPE_SEQUENCE",
	}
	EmbeddedSource_GeneratorType_value = map[string]int32{
		"GENERATOR_TYPE_UNSPECIFIED": 0,
		"GENERATOR_TYPE_SEQUENCE":    1,
	}
)

func (x EmbeddedSource_GeneratorType) Enum() *EmbeddedSource_GeneratorType {
	p := new(EmbeddedSource_GeneratorType)
	*p = x
	return p
}

func (x EmbeddedSource_GeneratorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmbeddedSource_GeneratorType) Descriptor() protoreflect.EnumDescriptor {
	return file_jobconfigpb_embedded_proto_enumTypes[0].Descriptor()
}

func (EmbeddedSource_GeneratorType) Type() protoreflect.EnumType {
	return &file_jobconfigpb_embedded_proto_enumTypes[0]
}

func (x EmbeddedSource_GeneratorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmbeddedSource_GeneratorType.Descriptor instead.
func (EmbeddedSource_GeneratorType) EnumDescriptor() ([]byte, []int) {
	return file_jobconfigpb_embedded_proto_rawDescGZIP(), []int{0, 0}
}

type EmbeddedSource struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	SplitCount    int32                        `protobuf:"varint,1,opt,name=split_count,json=splitCount,proto3" json:"split_count,omitempty"`
	BatchSize     int32                        `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Generator     EmbeddedSource_GeneratorType `protobuf:"varint,3,opt,name=generator,proto3,enum=dev.reduction.jobconfig.EmbeddedSource_GeneratorType" json:"generator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddedSource) Reset() {
	*x = EmbeddedSource{}
	mi := &file_jobconfigpb_embedded_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedSource) ProtoMessage() {}

func (x *EmbeddedSource) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_embedded_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedSource.ProtoReflect.Descriptor instead.
func (*EmbeddedSource) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_embedded_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddedSource) GetSplitCount() int32 {
	if x != nil {
		return x.SplitCount
	}
	return 0
}

func (x *EmbeddedSource) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *EmbeddedSource) GetGenerator() EmbeddedSource_GeneratorType {
	if x != nil {
		return x.Generator
	}
	return EmbeddedSource_GENERATOR_TYPE_UNSPECIFIED
}

var File_jobconfigpb_embedded_proto protoreflect.FileDescriptor

var file_jobconfigpb_embedded_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x62, 0x2f, 0x65, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x64, 0x65,
	0x76, 0x2e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xf3, 0x01, 0x0a, 0x0e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x70, 0x6c, 0x69,
	0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73,
	0x70, 0x6c, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x35, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x65, 0x64, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x4c, 0x0a,
	0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x1a, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b,
	0x0a, 0x17, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x53, 0x45, 0x51, 0x55, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jobconfigpb_embedded_proto_rawDescOnce sync.Once
	file_jobconfigpb_embedded_proto_rawDescData = file_jobconfigpb_embedded_proto_rawDesc
)

func file_jobconfigpb_embedded_proto_rawDescGZIP() []byte {
	file_jobconfigpb_embedded_proto_rawDescOnce.Do(func() {
		file_jobconfigpb_embedded_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobconfigpb_embedded_proto_rawDescData)
	})
	return file_jobconfigpb_embedded_proto_rawDescData
}

var file_jobconfigpb_embedded_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobconfigpb_embedded_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jobconfigpb_embedded_proto_goTypes = []any{
	(EmbeddedSource_GeneratorType)(0), // 0: dev.reduction.jobconfig.EmbeddedSource.GeneratorType
	(*EmbeddedSource)(nil),            // 1: dev.reduction.jobconfig.EmbeddedSource
}
var file_jobconfigpb_embedded_proto_depIdxs = []int32{
	0, // 0: dev.reduction.jobconfig.EmbeddedSource.generator:type_name -> dev.reduction.jobconfig.EmbeddedSource.GeneratorType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jobconfigpb_embedded_proto_init() }
func file_jobconfigpb_embedded_proto_init() {
	if File_jobconfigpb_embedded_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobconfigpb_embedded_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobconfigpb_embedded_proto_goTypes,
		DependencyIndexes: file_jobconfigpb_embedded_proto_depIdxs,
		EnumInfos:         file_jobconfigpb_embedded_proto_enumTypes,
		MessageInfos:      file_jobconfigpb_embedded_proto_msgTypes,
	}.Build()
	File_jobconfigpb_embedded_proto = out.File
	file_jobconfigpb_embedded_proto_rawDesc = nil
	file_jobconfigpb_embedded_proto_goTypes = nil
	file_jobconfigpb_embedded_proto_depIdxs = nil
}
