// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: jobconfigpb/resolvable.proto

package jobconfigpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringVar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*StringVar_Value
	//	*StringVar_Param
	Kind          isStringVar_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringVar) Reset() {
	*x = StringVar{}
	mi := &file_jobconfigpb_resolvable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringVar) ProtoMessage() {}

func (x *StringVar) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_resolvable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringVar.ProtoReflect.Descriptor instead.
func (*StringVar) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_resolvable_proto_rawDescGZIP(), []int{0}
}

func (x *StringVar) GetKind() isStringVar_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StringVar) GetValue() string {
	if x != nil {
		if x, ok := x.Kind.(*StringVar_Value); ok {
			return x.Value
		}
	}
	return ""
}

func (x *StringVar) GetParam() string {
	if x != nil {
		if x, ok := x.Kind.(*StringVar_Param); ok {
			return x.Param
		}
	}
	return ""
}

type isStringVar_Kind interface {
	isStringVar_Kind()
}

type StringVar_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type StringVar_Param struct {
	Param string `protobuf:"bytes,2,opt,name=param,proto3,oneof"`
}

func (*StringVar_Value) isStringVar_Kind() {}

func (*StringVar_Param) isStringVar_Kind() {}

type Int32Var struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Int32Var_Value
	//	*Int32Var_Param
	Kind          isInt32Var_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32Var) Reset() {
	*x = Int32Var{}
	mi := &file_jobconfigpb_resolvable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Var) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Var) ProtoMessage() {}

func (x *Int32Var) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_resolvable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Var.ProtoReflect.Descriptor instead.
func (*Int32Var) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_resolvable_proto_rawDescGZIP(), []int{1}
}

func (x *Int32Var) GetKind() isInt32Var_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Int32Var) GetValue() int32 {
	if x != nil {
		if x, ok := x.Kind.(*Int32Var_Value); ok {
			return x.Value
		}
	}
	return 0
}

func (x *Int32Var) GetParam() string {
	if x != nil {
		if x, ok := x.Kind.(*Int32Var_Param); ok {
			return x.Param
		}
	}
	return ""
}

type isInt32Var_Kind interface {
	isInt32Var_Kind()
}

type Int32Var_Value struct {
	Value int32 `protobuf:"varint,1,opt,name=value,proto3,oneof"`
}

type Int32Var_Param struct {
	Param string `protobuf:"bytes,2,opt,name=param,proto3,oneof"`
}

func (*Int32Var_Value) isInt32Var_Kind() {}

func (*Int32Var_Param) isInt32Var_Kind() {}

var File_jobconfigpb_resolvable_proto protoreflect.FileDescriptor

var file_jobconfigpb_resolvable_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x62, 0x2f, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x64, 0x65, 0x76, 0x2e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f,
	0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x43, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x42, 0x0a, 0x08,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x42, 0x2e, 0x5a, 0x2c, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x64, 0x65,
	0x76, 0x2f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jobconfigpb_resolvable_proto_rawDescOnce sync.Once
	file_jobconfigpb_resolvable_proto_rawDescData = file_jobconfigpb_resolvable_proto_rawDesc
)

func file_jobconfigpb_resolvable_proto_rawDescGZIP() []byte {
	file_jobconfigpb_resolvable_proto_rawDescOnce.Do(func() {
		file_jobconfigpb_resolvable_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobconfigpb_resolvable_proto_rawDescData)
	})
	return file_jobconfigpb_resolvable_proto_rawDescData
}

var file_jobconfigpb_resolvable_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jobconfigpb_resolvable_proto_goTypes = []any{
	(*StringVar)(nil), // 0: dev.reduction.jobconfig.StringVar
	(*Int32Var)(nil),  // 1: dev.reduction.jobconfig.Int32Var
}
var file_jobconfigpb_resolvable_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobconfigpb_resolvable_proto_init() }
func file_jobconfigpb_resolvable_proto_init() {
	if File_jobconfigpb_resolvable_proto != nil {
		return
	}
	file_jobconfigpb_resolvable_proto_msgTypes[0].OneofWrappers = []any{
		(*StringVar_Value)(nil),
		(*StringVar_Param)(nil),
	}
	file_jobconfigpb_resolvable_proto_msgTypes[1].OneofWrappers = []any{
		(*Int32Var_Value)(nil),
		(*Int32Var_Param)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobconfigpb_resolvable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobconfigpb_resolvable_proto_goTypes,
		DependencyIndexes: file_jobconfigpb_resolvable_proto_depIdxs,
		MessageInfos:      file_jobconfigpb_resolvable_proto_msgTypes,
	}.Build()
	File_jobconfigpb_resolvable_proto = out.File
	file_jobconfigpb_resolvable_proto_rawDesc = nil
	file_jobconfigpb_resolvable_proto_goTypes = nil
	file_jobconfigpb_resolvable_proto_depIdxs = nil
}
