// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: jobconfigpb/stdio.proto

package jobconfigpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StdioSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Framing       *Framing               `protobuf:"bytes,1,opt,name=framing,proto3" json:"framing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioSource) Reset() {
	*x = StdioSource{}
	mi := &file_jobconfigpb_stdio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioSource) ProtoMessage() {}

func (x *StdioSource) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_stdio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioSource.ProtoReflect.Descriptor instead.
func (*StdioSource) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_stdio_proto_rawDescGZIP(), []int{0}
}

func (x *StdioSource) GetFraming() *Framing {
	if x != nil {
		return x.Framing
	}
	return nil
}

// Framing specifies how to separate messages for the stdio source
type Framing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Scheme:
	//
	//	*Framing_LengthEncoded
	//	*Framing_Delimited
	Scheme        isFraming_Scheme `protobuf_oneof:"scheme"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Framing) Reset() {
	*x = Framing{}
	mi := &file_jobconfigpb_stdio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Framing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Framing) ProtoMessage() {}

func (x *Framing) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_stdio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Framing.ProtoReflect.Descriptor instead.
func (*Framing) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_stdio_proto_rawDescGZIP(), []int{1}
}

func (x *Framing) GetScheme() isFraming_Scheme {
	if x != nil {
		return x.Scheme
	}
	return nil
}

func (x *Framing) GetLengthEncoded() *Framing_LengthEncodedScheme {
	if x != nil {
		if x, ok := x.Scheme.(*Framing_LengthEncoded); ok {
			return x.LengthEncoded
		}
	}
	return nil
}

func (x *Framing) GetDelimited() *Framing_DelimitedScheme {
	if x != nil {
		if x, ok := x.Scheme.(*Framing_Delimited); ok {
			return x.Delimited
		}
	}
	return nil
}

type isFraming_Scheme interface {
	isFraming_Scheme()
}

type Framing_LengthEncoded struct {
	LengthEncoded *Framing_LengthEncodedScheme `protobuf:"bytes,1,opt,name=length_encoded,json=lengthEncoded,proto3,oneof"`
}

type Framing_Delimited struct {
	Delimited *Framing_DelimitedScheme `protobuf:"bytes,2,opt,name=delimited,proto3,oneof"`
}

func (*Framing_LengthEncoded) isFraming_Scheme() {}

func (*Framing_Delimited) isFraming_Scheme() {}

type StdioSink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioSink) Reset() {
	*x = StdioSink{}
	mi := &file_jobconfigpb_stdio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioSink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioSink) ProtoMessage() {}

func (x *StdioSink) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_stdio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioSink.ProtoReflect.Descriptor instead.
func (*StdioSink) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_stdio_proto_rawDescGZIP(), []int{2}
}

type Framing_LengthEncodedScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Framing_LengthEncodedScheme) Reset() {
	*x = Framing_LengthEncodedScheme{}
	mi := &file_jobconfigpb_stdio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Framing_LengthEncodedScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Framing_LengthEncodedScheme) ProtoMessage() {}

func (x *Framing_LengthEncodedScheme) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_stdio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Framing_LengthEncodedScheme.ProtoReflect.Descriptor instead.
func (*Framing_LengthEncodedScheme) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_stdio_proto_rawDescGZIP(), []int{1, 0}
}

type Framing_DelimitedScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delimiter     []byte                 `protobuf:"bytes,1,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Framing_DelimitedScheme) Reset() {
	*x = Framing_DelimitedScheme{}
	mi := &file_jobconfigpb_stdio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Framing_DelimitedScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Framing_DelimitedScheme) ProtoMessage() {}

func (x *Framing_DelimitedScheme) ProtoReflect() protoreflect.Message {
	mi := &file_jobconfigpb_stdio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Framing_DelimitedScheme.ProtoReflect.Descriptor instead.
func (*Framing_DelimitedScheme) Descriptor() ([]byte, []int) {
	return file_jobconfigpb_stdio_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Framing_DelimitedScheme) GetDelimiter() []byte {
	if x != nil {
		return x.Delimiter
	}
	return nil
}

var File_jobconfigpb_stdio_proto protoreflect.FileDescriptor

var file_jobconfigpb_stdio_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x62, 0x2f, 0x73, 0x74,
	0x64, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x22, 0x49, 0x0a, 0x0b, 0x53, 0x74, 0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x3a, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x72, 0x61,
	0x6d, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x8c, 0x02,
	0x0a, 0x07, 0x46, 0x72, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x5d, 0x0a, 0x0e, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x34, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x72, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x12, 0x50, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x6f, 0x62, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x65,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x1a, 0x15, 0x0a, 0x13, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x1a, 0x2f, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x22, 0x0b, 0x0a, 0x09,
	0x53, 0x74, 0x64, 0x69, 0x6f, 0x53, 0x69, 0x6e, 0x6b, 0x42, 0x2e, 0x5a, 0x2c, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x72, 0x65, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6a, 0x6f,
	0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_jobconfigpb_stdio_proto_rawDescOnce sync.Once
	file_jobconfigpb_stdio_proto_rawDescData = file_jobconfigpb_stdio_proto_rawDesc
)

func file_jobconfigpb_stdio_proto_rawDescGZIP() []byte {
	file_jobconfigpb_stdio_proto_rawDescOnce.Do(func() {
		file_jobconfigpb_stdio_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobconfigpb_stdio_proto_rawDescData)
	})
	return file_jobconfigpb_stdio_proto_rawDescData
}

var file_jobconfigpb_stdio_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jobconfigpb_stdio_proto_goTypes = []any{
	(*StdioSource)(nil),                 // 0: dev.reduction.jobconfig.StdioSource
	(*Framing)(nil),                     // 1: dev.reduction.jobconfig.Framing
	(*StdioSink)(nil),                   // 2: dev.reduction.jobconfig.StdioSink
	(*Framing_LengthEncodedScheme)(nil), // 3: dev.reduction.jobconfig.Framing.LengthEncodedScheme
	(*Framing_DelimitedScheme)(nil),     // 4: dev.reduction.jobconfig.Framing.DelimitedScheme
}
var file_jobconfigpb_stdio_proto_depIdxs = []int32{
	1, // 0: dev.reduction.jobconfig.StdioSource.framing:type_name -> dev.reduction.jobconfig.Framing
	3, // 1: dev.reduction.jobconfig.Framing.length_encoded:type_name -> dev.reduction.jobconfig.Framing.LengthEncodedScheme
	4, // 2: dev.reduction.jobconfig.Framing.delimited:type_name -> dev.reduction.jobconfig.Framing.DelimitedScheme
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jobconfigpb_stdio_proto_init() }
func file_jobconfigpb_stdio_proto_init() {
	if File_jobconfigpb_stdio_proto != nil {
		return
	}
	file_jobconfigpb_stdio_proto_msgTypes[1].OneofWrappers = []any{
		(*Framing_LengthEncoded)(nil),
		(*Framing_Delimited)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobconfigpb_stdio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobconfigpb_stdio_proto_goTypes,
		DependencyIndexes: file_jobconfigpb_stdio_proto_depIdxs,
		MessageInfos:      file_jobconfigpb_stdio_proto_msgTypes,
	}.Build()
	File_jobconfigpb_stdio_proto = out.File
	file_jobconfigpb_stdio_proto_rawDesc = nil
	file_jobconfigpb_stdio_proto_goTypes = nil
	file_jobconfigpb_stdio_proto_depIdxs = nil
}
