#!/usr/bin/env bash
set -ue

./vendor/protoc/bin/protoc \
  --plugin=protoc-gen-go=./vendor/protoc-gen-go \
  --go_opt=paths=source_relative \
  --go_out=. \
  --plugin=protoc-gen-connect-go=./vendor/protoc-gen-connect-go \
  --connect-go_opt=paths=source_relative \
  --connect-go_out=. \
  handlerpb/handler.proto \
  kinesispb/kinesis.proto \
  testrunpb/testrun.proto \
  jobconfigpb/jobconfig.proto
