#!/usr/bin/env bash
set -ue

./bin/protoc/bin/protoc \
  --plugin=protoc-gen-go=./bin/protoc-gen-go \
  --go_opt=paths=source_relative \
  --go_out=. \
  --plugin=protoc-gen-connect-go=./bin/protoc-gen-connect-go \
  --connect-go_opt=paths=source_relative \
  --connect-go_out=. \
  handlerpb/handler.proto
