#!/usr/bin/env bash
set -ue

## protoc installation

# Make temporary directory for downloads
TMP_DIR=$(mktemp -d)

# Download and upzip file
PROTOC_RELEASE=https://github.com/protocolbuffers/protobuf/releases/download/v29.3/protoc-29.3-osx-aarch_64.zip
curl --location $PROTOC_RELEASE --output ${TMP_DIR}/protoc.zip
mkdir -p ./bin/protoc
unzip -o ${TMP_DIR}/protoc.zip -d ./bin/protoc
chmod u+x ./bin/protoc/bin/protoc

# Remove temporary files
rm -rf ${TMP_DIR}

## Other go tools installation

# Loop through the packages and install each one
TOOLS=(
  "connectrpc.com/connect/cmd/protoc-gen-connect-go@v1.18.1"
  "google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.3"
)
for PKG in "${TOOLS[@]}"; do
  GOBIN=$(pwd)/bin go install ${PKG}
done

# Check if globstar is available in the current Bash version
if ! shopt -s globstar; then
    echo "Error: globstar is not supported in this version of Bash."
    echo $(bash --version)
    exit 1
fi
